import { ReactElement } from 'react';
import Head from 'next/head';
import Header from './header';
import Footer from './footer';
import styles from '../styles/Home.module.css'

type LayoutProps = Required<{
  readonly children: ReactElement
}>

export default function Layout({ children }: LayoutProps) {
  console.log('children', children);

  const title = !children.props.title ? 'Hello Next.js' : `${children.props.title} | Hello Next.js`;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Header />
        <main className={styles.main}>{children}</main>
        <Footer />
      </div>
    </>
  );
}